const nameGirl = 'To:Hoang Anh';
const giftUrl = 'https://www.facebook.com/groups/165460116804572';
const eventName = 'Happy 8/3 !!!';
const titleCard = 'For Vessalius';
const contentCard = '</br> Chào nhà tiên tri số 1 của tui ! </br> Mình rất vui vì được trở thành bạn của cậu và mình hy vọng sau này vẫn thế !  </br> Chúng ta chưa từng gặp nhau nhưng ngày đó sẽ đến sớm thôi. </br>Ở đây có socola vị bạc hà chờ sẵn nè !</br> Chúc cậu có ngày 8/3 và 320 ngày còn lại trong năm 2022 hạnh phúc và vui vẻ . </br></br> From 07.29 with luv';
const giftImage = 'vuduong.jpg';
const giftBg = 'valentines.jpg'
const base64 = '';
const giftImageBase64 = "data:image/jpg;base64, " + base64;